# Generated by Django 6.0.7 on 2026-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uninest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="monnify_reference",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="monnify_transaction_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
