# Generated by Django 6.0.7 on 2026-08-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Uninest", "0002_payment_monnify_reference_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="monnify_reference",
            new_name="paystack_reference",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="monnify_transaction_reference",
        ),
    ]
