# Generated by Django 6.0.7 on 2026-08-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Uninest",
            "0003_rename_monnify_reference_payment_paystack_reference_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rent_payments",
                to="Uninest.listing",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("subscription", "Subscription"),
                    ("rent", "Rent Payment"),
                    ("other", "Other"),
                ],
                default="subscription",
                max_length=20,
            ),
        ),
    ]
