# Generated by Django 6.0.7 on 2026-08-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Uninest", "0005_user_email_verified_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Staff-curated: shows in Featured Listings on the landing page.",
            ),
        ),
    ]
